name: CI with Docker Compose

on:
  push:
    branches: [ "master" ]   # אם אצלך הענף נקרא אחרת – להתאים

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Print simple message
        run: echo "Push to main detected. Running Docker Compose tests..."

      - name: Run tests using Docker Compose
        run: |
          docker compose up --build --abort-on-container-exit
          docker compose down
